### ISSUE TITLE
H.Hooks starts in a different thread than Application thread

### ISSUE THREAD

**Issue by akash07k** [HavenDV/H.Hooks#4]
So I'm creating a WinUI app and using H.Hooks from the App class which is derived from Application class.
However, I'm seing that App class is running on Thread ID 1 and All the keyboard events which are being intercepted by the H.Hooks are being run in thread ID 4.
Why so?
can I run H.Hooks in same thread as rest of the application?
Also, I'm handling the event by using
Hook.IsHandled = true

**Comment by HavenDV** [comment]
Running on a new thread happens because running the LowLevelHook requires it. If you try to run it on the main thread, it will cause terrible system lags on any attempt to debug or slow event handling.
Look into this to be able to cancel clicks: https://github.com/HavenDV/H.Hooks#interception-of-input-and-cancellation

**Comment by akash07k** [comment]
Thanks
